# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Sync labels in the declarative way"

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"

jobs:
  build:
    name: "Sync labels"

    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - uses: "crazy-max/ghaction-github-labeler@v4"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
